#!/bin/sh

# Make sure the OPENSEARCH_HOME environment variable is set
if [ -z "$OPENSEARCH_HOME" ]; then
    OPENSEARCH_HOME=/usr/share/opensearch
fi

# Cleanup files
if [ -d $OPENSEARCH_HOME/performance-analyzer-rca ]; then
  rm -rf $OPENSEARCH_HOME/performance-analyzer-rca
fi

if [ -f $OPENSEARCH_HOME/bin/performance-analyzer-agent-cli ]; then
  rm $OPENSEARCH_HOME/bin/performance-analyzer-agent-cli
fi

if [ -f "$OPENSEARCH_HOME"/data/rca_enabled.conf ]; then
  rm "$OPENSEARCH_HOME"/data/rca_enabled.conf
fi

if [ -f /var/lib/opensearch/performance_analyzer_enabled.conf ]; then
  rm /var/lib/opensearch/performance_analyzer_enabled.conf
fi

if [ -f /var/lib/opensearch/rca_enabled.conf ]; then
  rm /var/lib/opensearch/rca_enabled.conf
fi

if [ -f /usr/lib/systemd/system/opendistro-opensearch.service ]; then
  rm /usr/lib/systemd/system/opendistro-opensearch.service
fi
